"""add confidence breakdown

Revision ID: cba64ddf4a02
Revises: f070db4817a2
Create Date: 2026-07-04 17:54:33.786352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba64ddf4a02'
down_revision: Union[str, None] = 'f070db4817a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation_cases', sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigation_cases', 'confidence_breakdown')
    # ### end Alembic commands ###
